### PR TITLE
Delete invalid DOM attributes (#304)

### PR DESCRIPTION
**Pull request by klaasman**
I'm not sure whether you should merge this pull-request or not: it does fix the issue but I feel more for the `transitionProps`-solution as given by @Leeds-eBooks (https://github.com/Popmotion/popmotion/issues/304#issuecomment-397240840).

### CODE REVIEW

**Comment by Leeds-eBooks** [comment]
Would this work with React Native?

**Comment by klaasman** [comment]
Good point. The attribute validation function is borrowed from styled-components, which is react-native compatible. We'd need to dive into their codebase to see if there are other checks built in for native.

**Comment by InventingWithMonster** [comment]
@klaasman great PR! Looking forward to this. In SC do they outright delete invalid props or do they somehow not add them in the first place?

**Comment by Leeds-eBooks** [comment]
The more I think about it, the more I think there should be a `transitionProps` prop. Maintaining a list of valid DOM attributes is ok because they change rarely and everyone knows about upcoming changes to HTML. RN is a different beast, and having to maintain a list of accepted props for the various native components will be hard with such a fast-moving platform. Plus, asking devs to be explicit about which props they want passing down and which they only want to be used for pose functions is no bad thing in my opinion. If you want a prop to be used in both a pose function and to be passed through, you can just put it twice.

**Comment by InventingWithMonster** [comment]
@klaasman this is the approach I was thinking of https://github.com/styled-components/styled-components/blob/7aaf843b3983c7af9583c71a773a26341bfaf748/src/models/StyledComponent.js#L247

**Comment by InventingWithMonster** [comment]
I'd assume this works with RN but we'll have to test it out. RN stuff lives in `react-pose-core` anyway

**Comment by klaasman** [comment]
> The whole "picking" process should be also more efficient than copying first + deleting afterwards

Isn't your solution effectively doing the same thing, but then with a comparator for every key? (which sounds less efficient)

Nevertheless, your solution is fine too. With the default `isPropValid`-check it has the same behavior with the aforementioned additional benefits.

**Comment by klaasman** [comment]
There's this prop called the `poseKey`, which can be changed to re-trigger functions in the pose configuration. I'm thinking it might be possible to ditch this prop if we go for the `transitionProps` solution. Any thoughts on this?

**Comment by Andarist** [comment]
You iterate through all props when doing the initial merge (`{ ...this.getSetProps(), ...this.getRefs() }`), later you iterate through them again with `forEach` and you have to test each prop just like me to delete invalid ones. In general from what I know it's better to avoid deleting properties because it messes up hidden classes in JS engines (this might be outdated slightly at this point, but following a little what's going on in Chrome this should still be true - at least to some extent, maybe they are mitigating this deopt somehow nowadays).

My solution is ofc really similar - I just do a one pass iteration with `pickAssign` and the comparator test is done within this iteration. Additionally because `isValidProp` is a memoized function the comparator tests should be faster with time (because they will be looked up in a hash object instead of retesting the inputs each time with regexp).

As to `transitionProps` - personally I don't quite like it. IMHO makes the API more clunky *and* is easier to deopt the posed component (which extends PureComponent) by passing a new object reference in each render of the consuming component.

**Comment by InventingWithMonster** [comment]
Is isValidProp being memorised a potential source of server-side memory
leaks?

I agree that transitionProps is not my preferred solution. It feels
arbitrary and it’s unlikely we’ll be able to do a shallow compare as it
lends itself to setting as a new object in render. Which is why I think
it’s unlikely we’d be able to use it as a replacement for poseKey

**Comment by Andarist** [comment]
> Is isValidProp being memorised a potential source of server-side memory

The memoization is not weak, so theoretically this might be slight concern - but it shouldnt grow too much if you do not use thousands of different props (unlikely) and still the memory cost would be negligible. It's used in emotion which is popular css-in-js lib and we had no complaints about this and I know people are doing SSR with emotion.

**Comment by Leeds-eBooks** [comment]
>it’s unlikely we’ll be able to do a shallow compare as it lends itself to setting as a new object in render.

Given that `transitionProps` would be a direct replacement for props passed directly into the element, why couldn't you just shallow compare the top-level properties of the `transitionProps` object? You might thereby be able to deprecate the `poseKey` prop?

**Comment by klaasman** [comment]
I have to admit that transitionProps isn't my preferred solution either, bus it has its benefits. I think the shallow compare is possible, as @Leeds-eBooks states.

Another advantage is the freedom of how to name your props, e.g. currently the prop `value` will never work since it will be overridden by pose with a value object.

**Comment by Leeds-eBooks** [comment]
>Would break PureComponent's shallow compare

Is your `Box` element a posed component (e.g. a `posed.div()`)? If so, isn't it simply up to Pose to handle the `shouldComponentUpdate` logic? I think I must be missing something obvious!

**Comment by Andarist** [comment]
> Is your Box element a posed component (e.g. a posed.div())?

yeah

> If so, isn't it simply up to Pose to handle the shouldComponentUpdate logic? I think I must be missing something obvious!

Custom `shouldComponentUpdate` is an option. would have to change the base class of PoseElement to React.Component (from React.PureComponent), but that's minor thing. Seems to me like kinda reinventing the wheel when we can have shallow compare "for free" when using `PureComponent`. This has other costs though - keeping the props whitelist, filtering etc so maybe it would be worth it.

**Comment by InventingWithMonster** [comment]
@klaasman Thanks for this PR, I've been really pleased that the community has come together to tackle this one. But I'm going to close it in favour of [#431](https://github.com/Popmotion/popmotion/pull/431).

Reason being, from an API point of view these PRs are equivalent. But the other PR is using `@emotion/is-prop-valid` which will reduce filesize for users of both Pose and Emotion. It's also more maintainable than a regex. It might be possible for us to open a PR for Styled Components to see if they'd use the module too, so we can reduce filesize for more users.

To answer the other subject in this discussion - `transitionProps` is more explicit and would neatly sidestep this entire problem, but it brings complexities to the API which is against the single core principle of Pose (simplicity).

It also doubles up the props comparison, reimplementing something that React already does for us.  

It's true that the approach doesn't fix React Native, but then the userbase for React Native Pose is currently very low and it also uses its own version of `react-pose` anyway. It'd be possible, if no other solution was found, to implement `transitionProps` there. But I feel like it won't be necessary.

**Comment by Andarist** [comment]
> It's also more maintainable than a regex. It might be possible for us to open a PR for Styled Components to see if they'd use the module too, so we can reduce filesize for more users.

I'm planning to do it, a standard way of filtering the non-valid props would be beneficial to other libraries as well. Slight problem with `styled-components` is that their regexp is a little bit more complicated (i.e. validating the first character of data attributes) - IMHO it gives no real benefit, but ofc increases correctness, but sadly switching to other filtering function would a breaking change (sort of) for them. I know v4 is coming so maybe we could use that timing to start a discussion around this.

> It's true that the approach doesn't fix React Native, but then the userbase for React Native Pose is currently very low and it also uses its own version of react-pose anyway. It'd be possible, if no other solution was found, to implement transitionProps there. But I feel like it won't be necessary.

Emotion has similar testing function [here](https://github.com/emotion-js/emotion/blob/8edf5d33fe5ed26d3cc1bab24c03b0445e8cff56/packages/primitives/src/test-props.js), we could package it up too and unify React DOM & React Native pose libraries. The only difference would be which testing function gets configured as default for each one.

**Comment by klaasman** [comment]
@InventingWithMonster No problem! I'm glad there's movement with this issue 👍

**Comment by Andarist** [comment]
Just un update - styled-components are switching to `@emotion/is-prop-valid` too! https://github.com/styled-components/styled-components/pull/1937/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R65

**Pull request closed without merging**
