### PR TITLE
Remove dilate util (same as mix)

### PR DESCRIPTION
**Pull request by Andarist**
dilate & mix were the same thing and I think it's better to just keep one of them, personally i like dilate name slightly better because it's more descriptive (for me), although it's not entirely obvious what it does when at first (just by looking at the name) but it makes sense once i learn it

OTOH mix corresponds to mixColor, mixArray etc so maybe we should keep mix and remove dilate?

### CODE REVIEW

**Comment by InventingWithMonster** [comment]
Yeah this is a good point, though I'd remove `dilate` instead of `mix`.

**Comment by Andarist** [comment]
K. I'm going to change this PR later to do the opposite.

**Comment by Andarist** [comment]
I've changed the PR to remove `dilate` instead of `mix`

**Comment by InventingWithMonster** [comment]
Nice one thanks for this

**Comment by InventingWithMonster** [comment]
Published as `@popmotion/popcorn@0.2.0`

**Pull request merged**
