### PR TITLE
Fix merging of default drag/dragEnd configs with the ones specified b…

### LINKED ISSUE #729: React-Pose:  Draggable example no longer works
Per the documentation, the dragEnd should allow you to specify a location to transition to after the drag is released.  Instead, it chooses the location of the release of the drag.

1. Pull from: https://github.com/TonyLB/react-pose-bug
2. npm start

Expect the div in the middle of the page to always try to return to center when released.  It does not.

### PR DESCRIPTION
**Pull request by Andarist**
…y the user

fixes #729

### CODE REVIEW

**Comment by InventingWithMonster** [comment]
Thanks! Published as `react-pose@4.0.7`

**Comment by Andarist** [comment]
Not quite 😉 The fix was in `popmotion-pose` but you have only released `react-pose`

**Comment by Florian007** [comment]
In react-pose@4.0.8 popmotion-pose needs to be manually upgraded to min version popmotion-pose@3.4.7

**Comment by designbyadrian** [comment]
@Florian007 I've added popmotion-pose as a dependency and reinstalled react-pose, but still have this issue.

**Comment by Florian007** [comment]
> @Florian007 I've added popmotion-pose as a dependency and reinstalled react-pose, but still have this issue.

I do it automatically in the npm postinstall after every install to avoid doing it manually with the npm postinsall hook. You could add this to your scripts section in your package.json like so:

`"postinstall": "cd node_modules/react-pose && npm i popmotion-pose@3.4.7 && cd ../../"`

or do it manually.

**Comment by designbyadrian** [comment]
I tried that, then realised that with Yarn, you can add a resolutions field to package.json that does the same:

```json
dependencies: {  },
resolutions: {
  "popmotion-pose": "3.4.7"
}
```

Sadly, it didn't make any difference. `dragEnd` still doesn't work at all.

**Pull request merged**
