### PR TITLE
Allows click event on draggable element on mobile

### PR DESCRIPTION
**Pull request by dbismut**
This should fix https://github.com/Popmotion/popmotion/issues/541#issuecomment-445261912

I'm not exactly sure what's the best practice to add or remove listeners in popmotion, so code review would be much appreciated!

### CODE REVIEW

**Comment by dbismut** [comment]
Oh and I'm not exactly sure why CI fails, since it involves `popcorn/utils/interpolate.ts` which is untouched.

**Comment by Andarist** [comment]
Nice! I'm afraid I'm not competent enough to review this properly, so it will have to wait for @InventingWithMonster review.

As to tests - I believe I have fixed this in https://github.com/Popmotion/popmotion/pull/657 . You need to rebase your branch.

**Comment by Andarist** [comment]
@dbismut you've merged upstream branch into yours, which is fine! it works.

Rebase rewrite the git history by applying your new commits on top of the branch on which you want to rebase, co in a sense it fills a gap between some branch from which you have forked with missing commits, but keeps your commits as the most fresh ones. 

Either way is fine 👍

**Comment by dbismut** [comment]
I have, but not extensively. Only on my iPhone X running iOS 12 + Chrome Inspector. Here is the test code: https://codesandbox.io/s/wypk5zl40l (so obviously it only shows the bug on Codesandbox).

Also my understanding is that the `preventDefault` attribute in `events` was only used by `draggable`,  but I'm not exactly sure of any collaterals this PR may have with the rest of the framework.

Also one last thing: although this PR fixes clicks, it doesn't fix inner scroll in overflowing elements inside the `draggable` element. In #541 I've shown how to make it work (commented lines in the Codesandbox link), it would be technically doable to integrate this in `popmotion` directly but I'm not sure it's necessary (it would require looping on the DOM inside the draggable and get elements computed styles and adding listeners to the overflowing div, a bit ugly I guess unless there is a simpler way. Happy to elaborate if you'd like).

**Comment by dbismut** [comment]
@Andarist I'm so so sorry, but I have absolutely no idea how to do this... Is that `git rebase -i master`?

**Comment by Andarist** [comment]
> @Andarist I'm so so sorry, but I have absolutely no idea how to do this... Is that git rebase -i master?

You dont have to do it now, your merge is OK. I was just sharing some knowledge with you. And yeah `git rebase -i master` is one way to go, although it probably should be something like `upstream/master` because `master` is pointing to your local `master` branch.

**Comment by InventingWithMonster** [comment]
I'm not so concerned about scrollable elements within draggables as I think it's generally a bad idea, whereas this is a clear use case. Otherwise this looks good to me.

**Comment by dbismut** [comment]
@InventingWithMonster I had a situation where I used a `draggable` as a full page on mobile to be able to fully control the way it behaves on drag, release, and have functionalities close to what you can get on iOS native apps. So I needed to make sure overflowing inner-divs remained scrollable horizontally. But I agree, probably not a very common use case.

**Comment by InventingWithMonster** [comment]
Published in `popmotion-pose@3.4.1`

**Comment by JavierFVasquez** [comment]
If i want the upgraded features in 3.4.1 version , but in react-pose, what i can do?

**Comment by InventingWithMonster** [comment]
As a minor it should be enough to reinstall React-pose?

**Comment by dbismut** [comment]
@InventingWithMonster @Andarist Hey, I just realized my PR didn't prevent body scrolling on touch devices anymore when dragging a Drag element. I have a fix here https://github.com/Popmotion/popmotion/pull/706

Reaaaally sorry about this.

**Pull request merged**
