### PR TITLE
fixing pointer listener removal

### PR DESCRIPTION
**Pull request by FreakTheMighty**
The event listener wasn't removed because the anonymous functions being added and removed are not the same.

### CODE REVIEW

**Comment by FreakTheMighty** [comment]
This seems related to https://github.com/Popmotion/popmotion/issues/95

**Comment by FreakTheMighty** [comment]
Ah shoot, looks like the built file conflicts with master, and I've got some spurious white space. I will make a clean merge request.

**Comment by InventingWithMonster** [comment]
Thanks for this I'll be sure to merge when ready

**Comment by InventingWithMonster** [comment]
@FreakTheMighty Hi Jesse I've just made the same changes, I've credited you in the Changelog.

**Comment by FreakTheMighty** [comment]
Thanks, sorry I didn't get around to cleaning up the pull request.

**Pull request closed without merging**
