### PR TITLE
Add bounce easings

### LINKED ISSUE #743: Bounce Easing
**Is your feature request related to a problem? Please describe.**
The request is for a bounce type of easing, as described on https://easings.net/ (e.g. easeOutBounce). GreenSock is an example of another library with this functionality. As I use Popmotion for all my animation work, it would be great to have these easings in Popmotion too.

**Describe the solution you'd like**
Either built-in bounce easings, or allowing us to make new easings with Penner functions.

**Describe alternatives you've considered**
I have tried to manually implement Penner functions, but it is messy and not ideal when applying several different animations in parallel. See my CodePen example: https://codepen.io/magnusriga/pen/jJPJzB?editors=0111

### PR DESCRIPTION
**Pull request by Andarist**
closes #743

### CODE REVIEW

**Comment by magnusriga** [comment]
Thanks, @Andarist. Any idea when we can expect a merge?

**Comment by magnusriga** [comment]
Also, seems it was previously implemented and then somehow dropped at some point:

https://github.com/Popmotion/popmotion/pull/11/files/c19b614f63458a07ae5266c4d43c9e90bc60c60a..80401f56f76ff26d098d63b6d23a4fcd6bbb2342#diff-2e624fdc150cdabb493037ebbd78aa4f

**Comment by InventingWithMonster** [comment]
@magnusriga Yeah the reason I took it out was the idea that this kind of thing should be specifically handled by real physics. I do however understand the value of having it as part of a specific-duration animation.

I'll merge now but a publish might have to be Sunday/Monday

**Comment by magnusriga** [comment]
Thank you, @InventingWithMonster , and thanks for a terrific library.

**Comment by Andarist** [comment]
> Was you implementation based on the Penner function?

Sort of - yes.

**Comment by InventingWithMonster** [comment]
Published as `@popmotion/easing@1.0.2`

**Comment by magnusriga** [comment]
@InventingWithMonster

Thank you, Matt.

Would it be interesting if I implemented the other Penner function easings that are missing as well?

**Pull request merged**
