### PR TITLE
fix(stylefire): use css vendor prefix first

### LINKED ISSUE #679: compatibility problem
**Is your feature request related to a problem? Please describe.**

Browser: Android 4.4.4
Problem: popmotion uses CSS attr `transform` realize animation, it does not work in low version Android without prefix `-webkit-`.

**Describe the solution you'd like**

Autoprefix like `-webkit` `-moz-` `-ms-` `-o-` based on whether attr exists or not.

**Describe alternatives you've considered**

Nope.

**Additional context**

[Currently, is hard code here](https://github.com/Popmotion/popmotion/blob/master/packages/stylefire/src/css/build-styles.ts#L103)

### PR DESCRIPTION
**Pull request by Army-U**
Fixes #679

### CODE REVIEW

**Comment by Army-U** [comment]
Can anyone handle this PR?

**Comment by Army-U** [comment]
@InventingWithMonster

**Comment by InventingWithMonster** [comment]
Thanks for the prod, I'll take a look now

**Comment by ssehacker** [comment]
+1, my application looks weird in iPhone 6 since  iPhone 6 support transform with webkit prefix.

**Comment by InventingWithMonster** [comment]
Closed for inactivity

**Comment by LBRDan** [comment]
Actually, this is a real issue.
I'm working with `framer-motion`, and tracking this bug down was really though as it is a silent fail (Getting things worst, some legacy platforms don't display anything in style visually inside the devtools)
This PR seems legit (test aside)... maybe the array case change is an overkill as in operator comparison is case insensitive ( Warn: information not confirmed and not specified in the specs either https://tc39.es/ecma262/#sec-relational-operators but implemented insensitive for the most)
Is there a chance to see this fix to be merged anytime soon?
@InventingWithMonster

**Comment by LBRDan** [comment]
Any chance on viewing this merged ?

**Pull request closed without merging**
